version: '3.9'
services:
  db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./mongo/.env
    networks:
      - app-network
    volumes:
      - dbdata:/data/db

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: storage
    restart: unless-stopped
    volumes:
      - ./storage/files:/files
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local